### ISSUE TITLE
Running the script fails with network time outs

### ISSUE THREAD

**Issue by Raze** [brycepg/fto-scraper#1]
[error_output.txt](https://github.com/brycepg/fto-scraper/files/130783/error_output.txt)

**Comment by brycepg** [comment]
Can you `ping http://faerytaleonline.com/` on that machine?

**Comment by brycepg** [comment]
This is working fine on my machine. Things I can think of not making this work: a firewall, no network connection, IP ban by faerytaleonline.com. 

Since the connection timed out and was not refused, I'm thinking it might be more of a network issue on your end.

**Comment by brycepg** [comment]
Apparently you need to ping it without the protocol or the www. subdomain
This is very weird. Curl doesn't work on the website in most cases and I have a suspicion that it is actually causing the website to crash

**Comment by Raze** [comment]
Well ping seems to work. As do the script, maybe it was a temp ban due to me running curl? I don't know, but I'll set up the cron now and see how long it works.
