### ISSUE TITLE
With 1 data point, fto-graph.py issues warning and produces empty graph

### ISSUE THREAD

**Issue by joodicator** [brycepg/fto-scraper#3]
For example, with `fto.csv` having these contents:

```
Date,Population,Birth Queue,Pregnant Mothers
06/28/16-03,297,318,6
```

This is the console output:

```
$ ./fto-graph.py fto.csv
/usr/lib/python2.7/dist-packages/matplotlib/axes/_base.py:2782: UserWarning: Attempting to set identical left==right results
in singular transformations; automatically expanding.
left=736143.125, right=736143.125
  'left=%s, right=%s') % (left, right))
```

And this is `output.png`:
![output](https://cloud.githubusercontent.com/assets/14934117/16403190/98080ff0-3cea-11e6-975d-1f697b4aa218.png)

Other relevant information:

```
$ python --version
Python 2.7.10rc1
$ python -c 'print __import__("matplotlib").__version__'
1.5.2rc2
$ python -c 'print __import__("pandas").__version__'
0.18.0+git114-g6c692ae
```

The expected behaviour would be that it produces a graph with a single data point, or at least does not write a warning to the console. I realise this isn't a very important issue, but I thought it would be good to note it.

**Comment by brycepg** [comment]
I decided to call matplotlib directly instead of relying on pandas for the plotting part, which did get rid of this warning. However no data will show up with one data point(and I'm ok with that). Two data points will get you a nice straight line.
